services:
  nodebb:
    image: ghcr.io/nodebb/nodebb:latest
    restart: unless-stopped
    ports:
      - "4567:4567"
    environment:
      NODEBB_URL: https://nodebb152.de451.cloud
      NODEBB_DB: postgres
      NODEBB_DB_HOST: postgres
      NODEBB_DB_PORT: 5432
      NODEBB_DB_USER: nodebb
      NODEBB_DB_PASSWORD: nodebb
      NODEBB_DB_NAME: nodebb
      NODEBB_REDIS_HOST: redis
      NODEBB_REDIS_PORT: 6379
    volumes:
      - nodebb-data:/usr/src/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-alpine
    restart: unless-stopped

volumes:
  nodebb-data:
  postgres-data: